config/routes.rb
Lists::Application.routes.draw do
  
  resources :tasks
  root to: "tasks#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
    respond_to do |format|
      format.js { render :layout=>false }
    end
  end
  
  def index
    
  end
  
  def create
    @task = Task.new(params[:task])
    @task.save
    respond_to do |format|
      format.js { render :layout=>false }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lists</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<div id="loading-indicator">
<%= image_tag("ajax-loader.gif", :id => "loading", :style => "display:none") %>
</div>

</body>
</html>

app/views/tasks/_form.html.erb
<h1>New Task</h1>
<%= form_for(@task, :remote => true) do |f| %>
 <p>
 	<%= f.label :name %><br/>
 	<%= f.text_field :name %>
 </p>
 <p>
 	<%= f.label :description %></br/>
 	<%= f.text_field :description %>
 </p>
 <p class="button"><%= f.submit %></p>
<% end %>

app/views/tasks/_list.html.erb
<p>Name: <%= @task.name %></p>
<p>Description <%= @task.description %></p>

app/views/tasks/create.js.erb
$("#new_task").html("<%= escape_javascript(render(:partial => "list")) %>");

app/views/tasks/index.html.erb
<div id="new_task">
 <%= link_to "New Task", new_task_path, :remote => true %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for(@task, :remote => true) do |f| %>
 <p>
 	<%= f.label :name %>
 	<%= f.text_field :name %>
 </p>
 <p>
 	<%= f.label :description %>
 	<%= f.text_field :description %>
 </p>
 <p class="button"><%= f.submit %></p>
<% end %>

app/views/tasks/new.js.erb
$("#new_task").html("<%= escape_javascript(render(:partial => "form")) %>");